### ISSUE TITLE
Running vectorization on edge map of natural images

### ISSUE THREAD

**Issue by htzheng** [Vahe1994/Deep-Vectorization-of-Technical-Drawings#2]
Great work! Wondering if this method can convert the edge map of a natural image to a vectorized form? Thanks

**Comment by Vahe1994** [comment]
Hello, if I understood your question correctly, then technically yes. I don't see reasons why it should not. Although, it may require some adjustments:
1. If your input is grayscale segmented edges, then you can try to use the method as it is.
2. If as an input, you have an RGB image,  then use cleaning-part, as an edge detector(you should retrain U-net on edge segmentation task) . By doing so you will get a grayscale image(edges should be black, and background white)  and then use other modules for vectorization. 
 P.s. Vectorization can be not great, because of the domain difference between edge dataset and engineering. You can try to correct it,  by fine-tuning the model on your dataset.

If you have any question write me here or an email and I will try to help.

**Comment by htzheng** [comment]
That's great! I will try running the pretrained model on segmented edges and see the results. Thanks a lot for the detailed explanation!

**Comment by eleveneee** [comment]
> 真棒！我将尝试在分段边缘上运行预训练模型并查看结果。非常感谢您的详细解释！

Hei! bro, is it feasible for you to do this? How is the effect?
Looking forward to your reply!
